version: '3'
services:
  backend:
    build:
      context: ./news-backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: 127.0.0.1
      DB_DATABASE: news_db
      DB_USERNAME: root
      DB_PASSWORD: 
      MAIL_HOST: localhost
      MAIL_PORT: 1025
    volumes:
      - ./news-backend:/var/www/html
    ports:
      - 8000:8000
      - 1025:1025
    depends_on:
      - database
    networks:
      - news-network
  frontend:
    build:
      context: ./news-frontend
      dockerfile: Dockerfile
    volumes:
      - ./news-frontend:/app/src/app
    ports:
      - 3000:3000
    networks:
      - news-network
  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: news_db
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - news-network
networks:
  news-network: