version: '3'
services:

  backend:
    build:
      context: ./news-backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - './news-backend:/var/www/html'
    networks:
      - news-network

  frontend:
    build:
      context: ./news-frontend
      dockerfile: Dockerfile
    volumes:
      - ./news-frontend:/app
    ports:
      - 3000:3000
    networks:
      - news-network

  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: news_db
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 
    ports:
      - '3306:3306'
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - news-network

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_ARBITRARY: 1
    ports:
      - 9001:80
    networks:
      - news-network

networks:
  news-network:
    driver: bridge