version: '3'
services:
  backend:
    build:
      context: ./news-backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - './news-backend:/var/www/html'
    networks:
      - news-network
  frontend:
    build:
      context: ./news-frontend
      dockerfile: Dockerfile
    volumes:
      - ./news-frontend:/app
    ports:
      - 3000:3000
    networks:
      - news-network
  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: news_db
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - news-network
networks:
  news-network: